server:
  port: 7075
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api5        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
pdfDir: invoices/
reportFileName: invoice
reportFileNameDateFormat: dd_MMMM_yyyy
localDateFormat: '"dd MMMM yyyy HH:mm:ss"'
logoImgPath: logo.png
logoImgScale: 50,50
currencySymbol: $
table_noOfColumns: 4
table:
  columnNames: Item Name,Quantity,Unit Price,Net Price
aws:
  accessKey: ''
  secret: ''
  region: ''
  bucketName: ''
wati:
  notification:
    template:
      name: delivery_notification
  payment:
    reminder:
      template:
        name: payment_reminders
  send:
    template:
      msg:
        url: ''
  token: ''
